name: happypass_builder
description: Auto-gen http request code from happypass
version: 1.0.0
homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  analyzer: ">=0.39.0 <0.40.0"
  build:
  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  build_runner:
