name: happypass_builder
description: Auto-gen http request code from happypass
version: 1.0.2
homepage: https://github.com/CimZzz/happypass_builder

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  analyzer: ">=0.39.0 <0.40.0"
  build: ^1.0.0
  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  build_runner: ^1.0.0
